[package]
name = "techatlas-database"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
async-trait.workspace = true
secrecy.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
techatlas-common = { path = "../common" }
techatlas-models = { path = "../models" }
uuid.workspace = true

[dev-dependencies]
secrecy.workspace = true
techatlas-queue = { path = "../queue" }
testcontainers-modules = { version = "0.15.0", features = ["postgres"] }
